// Property Pulse daily board — data layer.
// Reads the lane snapshots generated by pulse_*_metrics.py (real AppFolio /
// Property Meld reads + renewals tracker) plus the entity registry
// (entities.json) that powers the entity-slice layer (master plan §6).
//
// Phase D contract: each lane snapshot MAY carry an optional `records` array
// of per-row facts alongside the `live` aggregate block. When records are
// present the board recomputes every displayed number through
// pulse-aggregate.ts (§6.4 honesty invariant); when absent it falls back to
// the generator's `live` block and entity scoping is unavailable.
import fs from 'fs';
import path from 'path';

// Committed synthetic fixtures (no real tenant data) used for PULSE_DEMO=1
// and by the §6.4 invariant tests. Never mix these with real snapshots.
import leasingFixture from './__fixtures__/pulse-slice/leasing-metrics.json';
import maintenanceFixture from './__fixtures__/pulse-slice/maintenance-metrics.json';
import financeFixture from './__fixtures__/pulse-slice/finance-metrics.json';
import turnsFixture from './__fixtures__/pulse-slice/turns-metrics.json';
import renewalsFixture from './__fixtures__/pulse-slice/renewals-metrics.json';
import evictionsFixture from './__fixtures__/pulse-slice/evictions-metrics.json';
import entitiesFixture from './__fixtures__/pulse-slice/entities.json';
import ownerFinancialsFixture from './__fixtures__/pulse-slice/owner-financials.json';
import assetMetricsFixture from './__fixtures__/pulse-slice/asset-metrics.json';
import ownerStatementsFixture from './__fixtures__/pulse-slice/owner-statements.json';
// Type-only import (erased at runtime — no import cycle): the OV-1 + asset-feed
// snapshot shapes live with the owner math in owner-aggregate.ts (§8.1 single
// module).
import type { OwnerFinancialsSnapshot, AssetMetricsSnapshot } from './owner-aggregate';
import type { OwnerStatementFeed } from './owner-reconcile-pull';

export interface LeasingFunnelStage {
  stage: string;
  count: number;
}

// ---------------------------------------------------------------------------
// Phase D records contract (per-entity rows the generators must emit)
// ---------------------------------------------------------------------------
// Every record carries the property dimension that AppFolio rows already have
// (PropertyId / PropertyName) plus the unit string. property_id is null ONLY
// where the join is genuinely unknown (pre-D-2 Meld records) — aggregation
// surfaces those as an explicit "unmapped" bucket, never silently drops them.

export interface PulseRecordBase {
  property_id: number | null;
  property_name: string | null;
  unit: string | null;
}

/**
 * Leasing lane records — one flat array, discriminated by `kind`, because the
 * lane's live block is fed by three row sources:
 *  - 'unit'        rent-roll unit rows        -> occupancy block
 *  - 'application' application report rows    -> applications + funnel
 *  - 'renewal'     renewals-tracker rows      -> renewal_retention block
 * Generators MUST emit only true unit rows as kind:'unit' (building-summary
 * rent-roll rows are excluded at emission — the §6.4 reconciliation trap).
 */
export type LeasingRecord =
  | (PulseRecordBase & {
      kind: 'unit';
      tenant_name: string | null;
      /** Generator-classified (single source of truth for the status→bucket
       *  mapping; TS only counts). Every emitted unit row is exactly one of
       *  these three — their sum IS the occupancy unit_basis. */
      occupancy_status: 'occupied' | 'vacant_available' | 'on_notice';
      /** Verbatim AppFolio status (Current / Vacant-Unrented / Evict / …). */
      status_raw: string;
      rent: number | null;
    })
  | (PulseRecordBase & {
      kind: 'application';
      applicant_name: string | null;
      status: 'approved' | 'denied' | 'canceled' | 'decision_pending' | 'new';
      /** True for approved apps currently converting to a lease. */
      converting: boolean;
      /** YYYY-MM-DD submission date. */
      submitted: string;
      /** Whole/fractional days submit→decision; null while undecided. */
      days_to_decision: number | null;
    })
  | (PulseRecordBase & {
      kind: 'renewal';
      tenant_name: string;
      /** Tracker status verbatim-normalized (not_started / out_for_signing / …). */
      status: string;
      lease_expiry: string | null;
    });

/**
 * Maintenance lane records — open melds plus melds completed in the last 7
 * days (and ONLY the last 7 days — completed_last_7d = count(state:'completed')).
 * `age_days` and `genuinely_unassigned` are generator-computed so the business
 * rules live in exactly one place; TS only counts and buckets.
 */
export type MaintenanceRecord = PulseRecordBase & {
  kind: 'meld';
  meld_id: number | string;
  /** Raw Meld address string — the D-2 join input; kept for audit. */
  address_raw: string;
  tenant_name?: string | null;
  state: 'open' | 'completed';
  priority: string; // EMERGENCY | HIGH | MEDIUM | LOW (Meld verbatim uppercase)
  genuinely_unassigned: boolean;
  /** Days open (generator-computed vs generated_at). null for completed. */
  age_days: number | null;
};

/**
 * Finance lane records — delinquency rows (INCLUDING zero-balance rows: they
 * count in totals but not in delinquent_accounts, mirroring
 * pulse_finance_metrics.py — the §6.4 trap) plus per-account deposit rows.
 */
export type FinanceRecord =
  | (PulseRecordBase & {
      kind: 'delinquency';
      tenant_name: string | null;
      balance: number;
      bucket_0_30: number;
      bucket_30_plus: number;
    })
  | (PulseRecordBase & {
      kind: 'deposit';
      tenant_name: string | null;
      deposit_held: number;
    });

/**
 * Turns lane records — one row per OPEN unit turn from /api/unit_turns
 * (master plan §6 records shape: turn_id/unit/property/move_out/target/
 * categories/wo_count). Completed turns are NOT emitted as records — the
 * completed_30d stat is a generator-level number from a second filtered call
 * (see TurnsMetrics.live.turnovers.completed_30d).
 */
export type TurnRecord = PulseRecordBase & {
  kind: 'turn';
  turn_id: number;
  /** YYYY-MM-DD move-out; null when AppFolio has no date on the turn. */
  move_out: string | null;
  /** YYYY-MM-DD target (rent-ready) date; null when unset. */
  target: string | null;
  /** Make-ready category name -> status string VERBATIM from AppFolio's
   *  unit_turn_category_status. The status enum is deliberately NOT typed —
   *  §4.5: render whatever distinct strings arrive, never assume an enum. */
  categories: Record<string, string>;
  /** Open work orders attached to the turn (service_requests.work_orders). */
  wo_count: number | null;
};

/**
 * Renewals lane records — one row per renewals-tracker tenant, promoted out
 * of the leasing snapshot into its own lane (master plan §4.2/§5.2, shard
 * C-1). Emitted by pulse_renewals_metrics.py, which reads ONLY on-disk
 * tracker_rows.json (zero AppFolio/network access from that script). See the
 * generator's module docstring for the exact data-gap notes this shape works
 * around: no tracker `stage` field exists yet (status falls back to the AF
 * lease renewal_status when the join has matched, else agent_recommendation);
 * no numeric property_id exists in the on-disk tracker (property_id is always
 * null here — the "unmapped" convention already used for pre-D-2 melds).
 */
export type RenewalsRecord = PulseRecordBase & {
  kind: 'renewal';
  tenant_name: string | null;
  /** Verbatim status bucket key — never a hardcoded enum (§4.5-style rule
   *  applied here too): render whatever string the generator assigned. */
  status: string;
  /** YYYY-MM-DD lease end date; null when the tracker has no date on file
   *  (rendered as "n/a" by the lane — never an em dash). */
  lease_expiry: string | null;
  /** Generator-computed: row falls inside the ~90-day renewal intake window
   *  (renewals_score.py's own in_intake_window flag, passed through verbatim
   *  — the business rule lives in exactly one place, the Python engine). */
  in_window: boolean;
  /** Generator-computed: the AF lease's own renewal_status (via
   *  join_leasing.py) equals 'out_for_signing'. Passed through verbatim. */
  out_for_signing: boolean;
};

/**
 * Evictions lane records — one row per rent-roll unit with Status=Evict
 * (master plan §4.3/§5.3, shard C-2 quick-wire). Emitted by
 * pulse_evictions_metrics.py, which reads ONLY on-disk rent_roll.csv +
 * delinquency.csv (zero AppFolio/network access). Both CSVs are AppFolio
 * "grouped by property" exports (a "-> <label> - <address>" header row above
 * each property's data rows, not a flat PropertyId/PropertyName column) — the
 * generator reuses the canonical `parse_grouped` parser for this shape rather
 * than reimplementing it, so property_id is always null here (no numeric id
 * exists anywhere in the on-disk CSVs, the same "unmapped" gap already used
 * for renewals and pre-D-2 melds); property_name carries the group-header
 * label string instead. See the generator's module docstring for the
 * delinquency-join finding this shape works around: today's on-disk
 * delinquency.csv matches 0 of the current Evict rows by (property, tenant
 * name) — these tenants appear to already be absent from that report once
 * eviction proceedings started — so `balance` falls back per-record to the
 * rent-roll row's own Past Due figure (`balance_source` says which was used)
 * and `last_payment` (needed for the oldest-eviction-age proxy) is null until
 * a match exists.
 */
export type EvictionsRecord = PulseRecordBase & {
  kind: 'eviction';
  tenant_name: string | null;
  /** YYYY-MM-DD move-out date; null while the eviction is still in progress
   *  (the common case — AppFolio has no move-out on file yet). */
  move_out: string | null;
  /** Dollar balance owed. Real number, sourced per `balance_source` — never
   *  fabricated; 0 only when genuinely no source had a figure (see below). */
  balance: number;
  /** Where `balance` came from: the delinquency join when it matched this
   *  tenant, else the rent-roll row's own Past Due column (a real, on-disk
   *  figure from the same daily pull — not a guess), else 'unavailable' (0)
   *  on the rare row with neither. Never silently drops the row (§4.3 edge
   *  case: evicting with no balance on file is itself worth showing). */
  balance_source: 'delinquency' | 'rent_roll_past_due' | 'unavailable';
  /** YYYY-MM-DD last payment date from the delinquency join; null when the
   *  join has no match for this tenant (true for every record on today's
   *  on-disk data — see the generator's needs_verification.delinquency_join).
   *  Feeds the §4.3 oldest-eviction-age proxy (aggregateEvictions computes
   *  the max age from whichever records DO have a date, mirroring
   *  aggregateTurns' oldest_days-from-move_out convention). */
  last_payment: string | null;
};

// ---------------------------------------------------------------------------
// Entity registry (entities.json, emitted by pulse_entities.py — §6.2)
// ---------------------------------------------------------------------------
export interface EntityRegistry {
  generated_at: string;
  properties: { id: number; name: string; owner_id: string | null }[];
  owners: { id: string; name: string; group: string | null }[];
  /** slug -> group. Seeded from David's owner-groups.json config (§6.3). */
  owner_groups: Record<string, { label: string; owners: string[] }>;
  /** Derived from rent-roll Current/Evict/Notice rows. `key` is the URL scope
   *  key: slug(name) + '--' + slug(unit) (names collide; units disambiguate). */
  residents: { key: string; name: string; unit: string; property_id: number }[];
  /** Property ids with no resolved owner — must be 0 or explained (§6.3). */
  unowned?: number[];
}

// ---------------------------------------------------------------------------
// Lane snapshot shapes
// ---------------------------------------------------------------------------
export interface LeasingMetrics {
  generated_at: string;
  today: string;
  live: {
    applications: {
      total: number;
      submitted_30d: number;
      submitted_90d: number;
      status_breakdown: Record<string, number>;
      converting_now: number;
      approval_rate_pct: number | null;
      median_days_to_decision: number | null;
    };
    funnel: LeasingFunnelStage[];
    occupancy:
      | {
          status: 'live';
          occupied_units: number;
          vacant_available: number;
          on_notice: number;
          unit_basis: number;
          occupancy_rate_pct: number | null;
          vacancy_rate_pct: number | null;
          basis_note: string;
        }
      | { status: 'coming_soon'; needs: string; error?: string };
    renewal_retention:
      | { status: 'live'; intake_window_rows: number; by_status: Record<string, number> }
      | { status: 'coming_soon'; needs: string; error?: string };
  };
  /** Phase D: per-row facts. Optional — absent until records emission lands. */
  records?: LeasingRecord[];
  needs_verification: Record<string, { why: string; [k: string]: unknown }>;
  coming_soon: Record<string, { needs: string }>;
}

export interface MaintenanceMetrics {
  generated_at: string;
  live: {
    open_work_orders: number;
    genuinely_unassigned: number;
    emergency: number;
    high_priority: number;
    priority_breakdown: Record<string, number>;
    aging_buckets: Record<string, number>;
    oldest_open_days: number | null;
    completed_last_7d: number | null;
  };
  /** Phase D: per-row facts. Optional — absent until records emission lands. */
  records?: MaintenanceRecord[];
  coming_soon: Record<string, { needs: string }>;
  /** Optional data-caution warnings (maintenance rarely has one; keeps the
   *  DataCaution render path uniform across every lane). */
  needs_verification?: Record<string, { why: string; [k: string]: unknown }>;
}

export interface FinanceMetrics {
  generated_at: string;
  live: {
    delinquency: {
      total_receivable: number;
      delinquent_accounts: number;
      bucket_0_30: number;
      bucket_30_plus: number;
    };
    deposits_held: { status: 'live'; total: number; accounts: number } | { status: 'coming_soon'; needs: string };
    /** Cash position (F-1). operating = the cash-flow statement's Actual Ending
     *  Cash (real, its own number). trust = the actual trust BANK balance, which
     *  is NOT available (coming_soon pending a bank feed). deposits_held above is
     *  the trust LIABILITY, never the bank balance; the two are never summed. */
    cash_position: {
      operating: { status: 'live'; balance: number; as_of: string } | { status: 'coming_soon'; needs: string };
      trust: { status: 'coming_soon'; needs: string };
    };
  };
  /** Phase D: per-row facts. Optional — absent until records emission lands. */
  records?: FinanceRecord[];
  needs_verification: Record<string, { why: string; [k: string]: unknown }>;
  coming_soon: Record<string, { needs: string }>;
}

/**
 * Turnovers + Make-Ready — ONE snapshot (one source, /api/unit_turns) feeding
 * BOTH sub-areas of the shared lane section (§4.4 + §4.5). Emitted by
 * pulse_turns_metrics.py (shard B-1 — see deliverables/pulse-turns-hookup-runbook.md).
 */
export interface TurnsMetrics {
  generated_at: string;
  /** YYYY-MM-DD the generator ran — the anchor for every day-math recompute. */
  today: string;
  live: {
    turnovers: {
      open_count: number;
      /** AppFolio's own portfolio stat (meta.stats.unit_turns.average_turn_days
       *  — NOT top-level, §5.4). Feed-level: per-turn durations are not in
       *  records, so this is passthrough under ALL and n/a under any scope. */
      avg_turn_days: number | null;
      /** Open turns whose target date is already behind us (target < today). */
      past_target: number;
      /** Second call with filter[completed]=true + completed_at window.
       *  Feed-level (completed turns emit no records): passthrough under ALL,
       *  n/a under any scope. null = generator could not compute it. */
      completed_30d: number | null;
      /** Days since move_out of the oldest open turn; null if none dated. */
      oldest_days: number | null;
      /** Open turns by days-since-move-out: 0-14d / 15-30d / 31-60d / 60d+.
       *  Turns with no move_out date are counted in open_count but not here. */
      age_buckets: Record<string, number>;
    };
    make_ready: {
      /** The configured make-ready categories in AppFolio sort order (from
       *  /api/unit_turn_setting_categories). Feed config, not a metric —
       *  passthrough verbatim under every scope; the pipeline widget's rows. */
      categories_in_order: string[];
      /** category name -> status string (VERBATIM) -> count of open turns.
       *  Only observed category/status pairs appear — no invented zeros. */
      category_status_counts: Record<string, Record<string, number>>;
      /** Open turns with zero WOs attached — nobody is working them. */
      stalled_zero_wo: number | null;
      /** Sum of open WOs attached across open turns. */
      open_wos_on_turns: number | null;
      /** Open turns with a target date 0-7 days out (due, not overdue —
       *  overdue turns are counted in past_target instead). */
      rent_ready_this_week: number;
    };
  };
  /** Phase D records — one per OPEN turn. Optional until B-1 lands live. */
  records?: TurnRecord[];
  needs_verification: Record<string, { why: string; [k: string]: unknown }>;
  coming_soon: Record<string, { needs: string }>;
}

/**
 * RENEWALS — its own lane (master plan §4.2, shard C-1). Emitted by
 * pulse_renewals_metrics.py from the renewals-tracker's daily on-disk export.
 * `ready_to_countersign` and `mtm` stay coming-soon chips (no confirmed data
 * source yet — see the generator docstring) rather than fabricated live
 * fields; only the buckets below are real numbers.
 */
export interface RenewalsMetrics {
  generated_at: string;
  /** YYYY-MM-DD the generator ran — the anchor for every day-math recompute. */
  today: string;
  live: {
    /** Tracker rows inside the ~90-day renewal intake window. */
    in_window: number;
    /** In-window rows not yet out for signing (in_window - out_for_signing). */
    not_started: number;
    /** In-window rows whose AF lease renewal_status is 'out_for_signing'. */
    out_for_signing: number;
    /** Rows with a lease_expiry 0-7 days out (regardless of window). */
    offers_expiring_7d: number;
    /** status -> count over EVERY row (including overdue/expired — never
     *  filtered out; §6.4-style reconciliation trap encoded in the tests). */
    by_status: Record<string, number>;
  };
  /** Phase D records — one per tracker row. */
  records?: RenewalsRecord[];
  needs_verification: Record<string, { why: string; [k: string]: unknown }>;
  coming_soon: Record<string, { needs: string }>;
}

/**
 * EVICTIONS — compact lane (master plan §4.3, shard C-2 quick-wire). Emitted
 * by pulse_evictions_metrics.py from the daily on-disk rent_roll.csv +
 * delinquency.csv pull (zero new AppFolio access). `filing_stage` and
 * `court_dates` stay coming-soon chips (§5.7 deep pipeline, no source yet).
 */
export interface EvictionsMetrics {
  generated_at: string;
  /** YYYY-MM-DD the generator ran — the anchor for every day-math recompute. */
  today: string;
  live: {
    /** Rent-roll rows with Status=Evict. */
    units_in_eviction: number;
    /** Sum of record balances (see EvictionsRecord.balance_source). */
    balance_at_risk: number;
    /** Days since last payment, over whichever records have one (§4.3 proxy).
     *  null when no record in scope has a last_payment date — true for every
     *  record today (0-match delinquency join, see needs_verification). */
    oldest_eviction_age_days: number | null;
    /** Notice-Rented + Notice-Unrented rows — a related sub-stat, NOT emitted
     *  as its own records (a different population than the Evict records
     *  above), so it is feed-level: passthrough under ALL scope, n/a under
     *  any narrower scope (same convention as TurnsMetrics.avg_turn_days).
     *  null ONLY under a narrower scope (the aggregate's na.move_outs_pending
     *  explains why) — the generator itself always emits a real number. */
    move_outs_pending: number | null;
  };
  /** Phase D records — one per Evict-status unit. */
  records?: EvictionsRecord[];
  needs_verification: Record<string, { why: string; [k: string]: unknown }>;
  coming_soon: Record<string, { needs: string }>;
}

// .pulse-data holds real tenant/financial snapshots and is GITIGNORED — never commit it.
// Generated locally per pull; on a fresh deploy/clone the dir is absent and read() returns null.
// Files are only ever read server-side through fs — never web-served as static assets (§6.6).
function read<T>(file: string): T | null {
  try {
    return JSON.parse(fs.readFileSync(path.join(process.cwd(), '.pulse-data', file), 'utf-8')) as T;
  } catch {
    return null;
  }
}

// Demo mode: PULSE_DEMO=1 serves the committed synthetic fixtures so the full
// slice UX (records + registry + scoping) is demoable without live data. The
// page shows an explicit "synthetic demo data" badge — fixture numbers must
// never be mistakable for real ones.
export const isPulseDemo = () => process.env.PULSE_DEMO === '1';

export const getLeasingMetrics = (): LeasingMetrics | null =>
  isPulseDemo() ? (leasingFixture as unknown as LeasingMetrics) : read<LeasingMetrics>('leasing-metrics.json');
export const getMaintenanceMetrics = (): MaintenanceMetrics | null =>
  isPulseDemo() ? (maintenanceFixture as unknown as MaintenanceMetrics) : read<MaintenanceMetrics>('maintenance-metrics.json');
export const getFinanceMetrics = (): FinanceMetrics | null =>
  isPulseDemo() ? (financeFixture as unknown as FinanceMetrics) : read<FinanceMetrics>('finance-metrics.json');
export const getTurnsMetrics = (): TurnsMetrics | null =>
  isPulseDemo() ? (turnsFixture as unknown as TurnsMetrics) : read<TurnsMetrics>('turns-metrics.json');
export const getRenewalsMetrics = (): RenewalsMetrics | null =>
  isPulseDemo() ? (renewalsFixture as unknown as RenewalsMetrics) : read<RenewalsMetrics>('renewals-metrics.json');
export const getEvictionsMetrics = (): EvictionsMetrics | null =>
  isPulseDemo() ? (evictionsFixture as unknown as EvictionsMetrics) : read<EvictionsMetrics>('evictions-metrics.json');
export const getEntities = (): EntityRegistry | null =>
  isPulseDemo() ? (entitiesFixture as unknown as EntityRegistry) : read<EntityRegistry>('entities.json');

// OV-1 per-property financial spine snapshot (owner dashboard §5). Same demo /
// .pulse-data pattern as the lane snapshots. Absent (null) until OV-1 lands
// live — the owner route renders an honest "data pending" shell in that case,
// never fabricated numbers (§8 owner-truth).
export const getOwnerFinancials = (): OwnerFinancialsSnapshot | null =>
  isPulseDemo()
    ? (ownerFinancialsFixture as unknown as OwnerFinancialsSnapshot)
    : read<OwnerFinancialsSnapshot>('owner-financials.json');

// AL-2 asset-metrics snapshot (RentCast AVM value + market rent). Same demo /
// .pulse-data pattern as the lane snapshots; absent (null) until the bounded
// RentCast pull runs — the value/rent cards stay honest ComingSoon in that case
// (§8.2), never fabricated. Real asset-metrics.json is gitignored (.pulse-data).
export const getAssetMetrics = (): AssetMetricsSnapshot | null =>
  isPulseDemo()
    ? (assetMetricsFixture as unknown as AssetMetricsSnapshot)
    : read<AssetMetricsSnapshot>('asset-metrics.json');

// A7 owner-statement reconciliation feed. Real data lives in .pulse-data and is
// server-read only. Demo mode uses committed synthetic owner statements matched
// to the synthetic owner-financials fixture.
export const getOwnerStatements = (): OwnerStatementFeed | null =>
  isPulseDemo()
    ? (ownerStatementsFixture as unknown as OwnerStatementFeed)
    : read<OwnerStatementFeed>('owner-statements.json');

// Pretty label for a coming-soon / needs-source slot key.
export function humanizeKey(k: string): string {
  return k.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}
