// AUTO-GENERATED by `cortextos ecosystem`. Do NOT edit by hand.
// Re-run `cortextos ecosystem` to regenerate.
//
// Note: env vars use process.env.X || 'default' so PM2 picks up the value
// from the calling shell at startup time. This means `CTX_INSTANCE_ID=foo
// pm2 restart cortextos-daemon` switches instances without regenerating.
const path = require('path');
const frameworkRoot = process.env.CTX_FRAMEWORK_ROOT || __dirname;
const instanceId = process.env.CTX_INSTANCE_ID || 'default';
const ctxRoot = process.env.CTX_ROOT || path.join(process.env.HOME || frameworkRoot, '.cortextos', instanceId);

module.exports = {
  apps: [
    {
      name: 'cortextos-daemon',
      script: path.join(frameworkRoot, 'dist', 'daemon.js'),
      args: '--instance ' + (process.env.CTX_INSTANCE_ID || "default"),
      cwd: frameworkRoot,
      env: {
        CTX_INSTANCE_ID: process.env.CTX_INSTANCE_ID || "default",
        CTX_ROOT: ctxRoot,
        CTX_FRAMEWORK_ROOT: frameworkRoot,
        CTX_PROJECT_ROOT: process.env.CTX_PROJECT_ROOT || frameworkRoot,
        CTX_ORG: process.env.CTX_ORG || "ascendops",
      },
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    },
    {
      name: 'cortextos-dashboard',
      script: 'npm',
      args: 'run dev',
      cwd: path.join(frameworkRoot, 'dashboard'),
      env: {
        PORT: process.env.PORT || '3000',
      },
      // Dashboard reads its real config from dashboard/.env.local — populated
      // by /onboarding Phase 7. PM2 just supervises the npm process.
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    },
  ],
};
